scrape_configs:
  - job_name: 'snmp_dynamic'
    file_sd_configs:
      - files:
        - 'targets.json'
    metrics_path: /snmp
    relabel_configs:
      # Map the "model" label from JSON to the "module" parameter
      - source_labels: [model]
        target_label: __param_module

      # Standard SNMP Relabeling...
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116